# Generated by Django 4.1.3 on 2022-11-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=10, null=True)),
                ('ano', models.DateField()),
                ('nome_professor', models.ManyToManyField(to='professor.professor')),
            ],
        ),
    ]
