# Generated by Django 4.1.3 on 2022-11-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='nome_professor',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='nome_professor',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
