# Generated by Django 4.1.3 on 2022-11-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0003_alter_disciplina_nome_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome_disciplina',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
