# Generated by Django 4.1.3 on 2022-11-08 00:59

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0004_alter_disciplina_nome_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='ano',
            field=models.DateField(validators=[base.validators.validateDate]),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome_disciplina',
            field=models.CharField(max_length=50, null=True, validators=[base.validators.validateNoDigits]),
        ),
    ]
