# Generated by Django 4.1.3 on 2022-11-29 20:00

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, validators=[base.validators.validateNome, base.validators.validateNoDigits])),
                ('email', models.CharField(max_length=100, null=True, unique=True, validators=[base.validators.validateEmail])),
                ('contato', models.CharField(max_length=11, null=True, validators=[base.validators.validateContato])),
                ('cpf', models.CharField(max_length=11, null=True, unique=True, validators=[base.validators.validateCpf])),
                ('rg', models.CharField(max_length=7, null=True, unique=True, validators=[base.validators.validateRg])),
                ('endereco', models.CharField(max_length=100, null=True, validators=[base.validators.validateEndereco])),
                ('data_nascimento', models.DateField()),
                ('data_entrada', models.DateField(validators=[base.validators.validateDate])),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Integral', 'Integral')], max_length=50, null=True)),
                ('departamento', models.CharField(choices=[('Coordenação', 'Coordenação'), ('Professor', 'Professor'), ('Aluno', 'Aluno')], max_length=50, null=True)),
            ],
        ),
    ]
