# Generated by Django 4.1.3 on 2022-11-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
