# Generated by Django 4.1.3 on 2022-11-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(choices=[('Coordenação', 'Coordenação'), ('Professor', 'Professor'), ('Aluno', 'Aluno')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Integral', 'Integral')], max_length=50, null=True),
        ),
    ]
