# Generated by Django 4.1.3 on 2022-11-08 00:59

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_departamento_alter_usuario_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_entrada',
            field=models.DateField(validators=[base.validators.validateDate]),
        ),
    ]
