# Generated by Django 4.1.3 on 2022-11-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroaula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroaula',
            name='num_aulas',
            field=models.IntegerField(),
        ),
    ]
