# Generated by Django 4.1.3 on 2022-11-29 20:00

import base.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_aluno', models.CharField(max_length=11, null=True, unique=True, validators=[base.validators.validateCpf])),
                ('nome_aluno', models.ForeignKey(limit_choices_to={'departamento': 'Aluno'}, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
