# Generated by Django 4.1.3 on 2022-11-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='historico',
            field=models.ImageField(null=True, upload_to='historicos/', verbose_name='Histórico'),
        ),
    ]
