# Generated by Django 4.1.3 on 2022-11-07 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_historico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='historico',
        ),
    ]
