# Generated by Django 4.1.3 on 2022-11-07 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('aluno', '0003_remove_aluno_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.ForeignKey(limit_choices_to={'departamento': 3}, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
