# Generated by Django 4.1.3 on 2022-11-08 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_data_entrada'),
        ('aluno', '0004_alter_aluno_nome_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.ForeignKey(limit_choices_to={'departamento': 'Aluno'}, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
