# Generated by Django 4.1.3 on 2022-11-10 11:27

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_alter_aluno_nome_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf_aluno',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[base.validators.validateCpf]),
        ),
    ]
