# Generated by Django 4.1.3 on 2022-11-29 20:00

import base.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau_formacao', models.CharField(choices=[('Graduado', 'Graduado'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=10, null=True)),
                ('formacao', models.CharField(max_length=20, null=True, validators=[base.validators.validateNoDigits])),
                ('nome_professor', models.ForeignKey(limit_choices_to={'departamento': 'Professor'}, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
