# Generated by Django 4.1.3 on 2022-11-07 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nome_professor',
            field=models.ForeignKey(limit_choices_to={'departamento': 2}, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
