# Generated by Django 4.1.3 on 2022-11-08 00:59

import base.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_data_entrada'),
        ('professor', '0003_alter_professor_grau_formacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='formacao',
            field=models.CharField(max_length=20, null=True, validators=[base.validators.validateNoDigits]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome_professor',
            field=models.ForeignKey(limit_choices_to={'departamento': 'Professsor'}, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
