# Generated by Django 4.1.3 on 2022-11-10 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_data_entrada'),
        ('professor', '0005_alter_professor_nome_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nome_professor',
            field=models.ForeignKey(limit_choices_to={'departamento': 'Professor'}, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', unique=True),
        ),
    ]
