# Generated by Django 4.1.3 on 2022-11-07 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0004_alter_aluno_nome_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('forma_pagamento', models.CharField(choices=[('cartão de crédito', 'cartão de crédito'), ('cartão de déito', 'cartão de débito'), ('pix', 'pix'), ('dinheiro', 'dinheiro')], max_length=50, null=True)),
                ('nome_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
    ]
