# Generated by Django 4.1.3 on 2022-11-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='data_pagamento',
            field=models.DateField(unique=True),
        ),
    ]
