# Generated by Django 4.1.3 on 2022-11-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidade', '0002_alter_mensalidade_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='data_pagamento',
            field=models.DateField(),
        ),
    ]
