# Generated by Django 4.1.3 on 2022-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidade', '0003_alter_mensalidade_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='valor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
